version: "3.8"

networks:
  develop_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.0.0/20
          gateway: 172.16.0.1

services:
  postgres:
    image: postgres:latest
    env_file:
      - ${PROJECT_DIR}/.env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d gorest-iman -U iman" ]
      interval: ${POSTGRES_HEALTHCHECK_INTERVAL}
      timeout: ${POSTGRES_HEALTHCHECK_TIMEOUT}
      retries: ${POSTGRES_HEALTHCHECK_RETRIES}
    ports:
      - "5432:5432"
    ulimits:
      nofile:
        soft: 524288
        hard: 524288
    networks:
      develop_net:
        ipv4_address: 172.16.0.100
    restart: always
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
      - ./sql/docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql